# buildbot/buildbot-worker-python-node

# This example docker file show how to customize the base worker docker image
# to add build dependencies to build the python+nodejs buildbot_www package

FROM        buildbot/buildbot-worker:master
MAINTAINER  Buildbot maintainers

# This will make apt-get install without question
ARG         DEBIAN_FRONTEND=noninteractive

user root
# Install required npm packages
RUN  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
        apt-get update && apt-get install -y -o APT::Install-Recommends=false -o APT::Install-Suggests=false \
        nodejs \
        afl \
        cppcheck \
        g++ \
        valgrind \
        wget \
        git && \
    wget -O /tmp/zzuf.deb http://mirrors.kernel.org/ubuntu/pool/universe/z/zzuf/zzuf_0.13.svn20100215-4_amd64.deb && \
    dpkg -i /tmp/zzuf.deb && \
    rm -rf /var/lib/apt/lists/*

user buildbot
